"""Update the query engine tools

Revision ID: 0cb7542c5f72
Revises: 1f3df2f9cadd
Create Date: 2023-11-30 13:55:26.570452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb7542c5f72'
down_revision: Union[str, None] = '1f3df2f9cadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('respondents')
    op.drop_table('proxy_respondents')
    op.drop_table('treatment_patterns')
    op.drop_table('net_promoter_scores')
    op.drop_table('colleagues')
    op.drop_table('completed_survey_respondents')
    op.drop_table('completed_survey')
    op.drop_table('demographics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demographics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('survey_year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_male_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_female_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_age', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='demographics_pkey')
    )
    op.create_table('completed_survey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='completed_survey_pkey')
    )
    op.create_table('completed_survey_respondents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='completed_survey_respondents_pkey')
    )
    op.create_table('colleagues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('given_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='colleagues_pkey')
    )
    op.create_table('net_promoter_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('survey_year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_survey_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='net_promoter_scores_pkey')
    )
    op.create_table('treatment_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('patients_followed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_with_pi_defect', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_receiving_ig_g_ivig_clinic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_receiving_ig_g_ivig_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_receiving_ig_g_scig', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_receiving_ig_g_other', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_with_gene_therapy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_with_peg_ada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_donor_type_mrd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_donor_type_mud', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_donor_type_m_mud', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_donor_type_haplo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_stem_cell_src_bm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_stem_cell_src_pbsc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_stem_cell_src_cord', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_stem_cell_src_other_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('patients_treated_by_transplant_stem_cell_src_other_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patients_diagnosed_through_jeffrey_insights_program', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='treatment_patterns_pkey')
    )
    op.create_table('proxy_respondents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('given_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='proxy_respondents_pkey')
    )
    op.create_table('respondents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('honorific_prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('honorific_suffix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_formatted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fax_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('international_dialing_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_office_box_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_international_dialing_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fax_international_dialing_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_newsletter_subscriber', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_administrator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='respondents_pkey')
    )
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patients_reported', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defect', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('omim_entry_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gene_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inheritance_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('respondent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_alternate_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('world_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_sub_region_alternate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='responses_pkey')
    )
    # ### end Alembic commands ###
