"""added agent step enum

Revision ID: 307164d47ded
Revises: 89b85f102cd5
Create Date: 2023-10-12 12:43:35.120702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307164d47ded'
down_revision: Union[str, None] = '89b85f102cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enums_to_add = ['TEMPLATING', 'FUNCTION_CALL',
                    'RERANKING', 'EXCEPTION', 'AGENT_STEP']
    for enum_val in enums_to_add:
        op.execute(f"""
            DO $$ 
            BEGIN
                BEGIN
                    -- Try to insert the enum value
                    ALTER TYPE "MessageSubProcessSourceEnum" ADD VALUE '{enum_val}';
                EXCEPTION 
                    WHEN duplicate_object THEN
                        -- Enum value already exists, do nothing
                        NULL;
                END;
            END $$;
        """)

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
