"""Initial migration

Revision ID: 832a21f82318
Revises: 
Create Date: 2023-09-27 17:04:04.234197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '832a21f82318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversation_id'),
                    'conversation', ['id'], unique=False)
    op.create_table('document',
                    sa.Column('table_name', sa.String(), nullable=False),
                    sa.Column('metadata_map', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('table_name')
                    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_table('conversationdocument',
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('document_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                                            'conversation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['document.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversationdocument_conversation_id'),
                    'conversationdocument', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversationdocument_document_id'),
                    'conversationdocument', ['document_id'], unique=False)
    op.create_index(op.f('ix_conversationdocument_id'),
                    'conversationdocument', ['id'], unique=False)
    op.create_table('message',
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('role', postgresql.ENUM('user', 'assistant',
                                                      name='MessageRoleEnum'), nullable=True),
                    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS',
                                                        'ERROR', name='MessageStatusEnum'), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                                            'conversation.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_conversation_id'),
                    'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('messagesubprocess',
                    sa.Column('message_id', sa.UUID(), nullable=True),
                    sa.Column('source', postgresql.ENUM('CHUNKING', 'NODE_PARSING', 'EMBEDDING', 'LLM', 'QUERY', 'RETRIEVE', 'SYNTHESIZE',
                              'TREE', 'SUB_QUESTION', 'CONSTRUCTED_QUERY_ENGINE', 'SUB_QUESTIONS', name='MessageSubProcessSourceEnum'), nullable=True),
                    sa.Column('status', postgresql.ENUM('PENDING', 'FINISHED',
                                                        name='MessageSubProcessStatusEnum'), nullable=False),
                    sa.Column('metadata_map', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messagesubprocess_id'),
                    'messagesubprocess', ['id'], unique=False)
    op.create_index(op.f('ix_messagesubprocess_message_id'),
                    'messagesubprocess', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messagesubprocess_message_id'),
                  table_name='messagesubprocess')
    op.drop_index(op.f('ix_messagesubprocess_id'),
                  table_name='messagesubprocess')
    op.drop_table('messagesubprocess')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversationdocument_id'),
                  table_name='conversationdocument')
    op.drop_index(op.f('ix_conversationdocument_document_id'),
                  table_name='conversationdocument')
    op.drop_index(op.f('ix_conversationdocument_conversation_id'),
                  table_name='conversationdocument')
    op.drop_table('conversationdocument')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
