"""Added headline to conversation

Revision ID: 89b85f102cd5
Revises: b8dba50d6249
Create Date: 2023-10-04 15:44:05.473991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b85f102cd5'
down_revision: Union[str, None] = 'b8dba50d6249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('headline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'headline')
    # ### end Alembic commands ###
