"""Add pgcrypto extension

Revision ID: 9c9e567fc9e6
Revises: 832a21f82318
Create Date: 2023-09-27 18:07:50.577418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9e567fc9e6'
down_revision: Union[str, None] = '832a21f82318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS pgcrypto;")
    pass
    # ### end Alembic commands ###
