"""Remove unique on email

Revision ID: a7ffcb154847
Revises: caa1260da93a
Create Date: 2025-06-20 02:01:21.633525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ffcb154847'
down_revision: Union[str, None] = 'caa1260da93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.drop_column('clients', 'client_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
