"""Add uuid-ossp extension

Revision ID: b8dba50d6249
Revises: 9c9e567fc9e6
Create Date: 2023-09-27 18:17:44.219522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dba50d6249'
down_revision: Union[str, None] = '9c9e567fc9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    pass
    # ### end Alembic commands ###
