"""change uuid usage

Revision ID: 007b621e23b4
Revises: a7ffcb154847
Create Date: 2025-06-20 02:17:55.247814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007b621e23b4'
down_revision: Union[str, None] = 'a7ffcb154847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'client_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'clients', ['client_number'])
    op.drop_constraint(op.f('transactions_client_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'clients', ['client_number'], ['client_number'])
    op.drop_column('transactions', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_client_id_fkey'), 'transactions', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='unique')
    op.alter_column('clients', 'client_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
